import type { NextPage } from 'next'
import Head from 'next/head'
import { MainMap } from '../components/MainMap'
import { MapCatchment } from '../components/MapCatchment'
import { Source, Layer } from "react-map-gl"
import { useEffect } from 'react'
import { useAtom } from 'jotai'
import { randomShapeAtom, updateShapeAtom } from '../atoms/randomShape'

const layerStyle = {
  id: 'point',
  type: 'fill',
  paint: {
    'fill-color': "rgba(45, 2, 156, 0.3)"
  }
};

const Home: NextPage = () => {
  const [randomShape] = useAtom(randomShapeAtom);
  const [, updateShape] = useAtom(updateShapeAtom);

  useEffect(() => {
    const token = setInterval(() => updateShape(), 200)

    return () => clearInterval(token)
  }, [updateShape])

  return (
    <>
      <Head>
        <title>Catchment Tryout</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div style={{ minHeight: '100vh', minWidth: '100vw', padding: 32, display: 'flex', justifyContent: 'center', alignItems: "center" }}>
        <div style={{ boxShadow: '1px 1px 20px rgba(0, 0, 0, 0.5)' }}>
          <MainMap>
            <MapCatchment longitude={10} latitude={10} />
            <Source id="my-data" type="geojson" data={randomShape}>
              <Layer {...layerStyle} />
            </Source>          </MainMap>
        </div>
      </div>
    </>
  )
}

export default Home
